let chrysosHeirs = [
  {
    id: "1",
    nombre: "Phainon",
    titulo: "The Blazing Sun That Burns Itself Away",
    path: "Destruction",
    elemento: "Physical",
    version: 3.4,
    isDeliverer: true,
    descripcion:
      "The Nameless hero, Khaslana, the Chrysos Heir carrying the Coreflame of Worldbearing, memorizes the ideals of the entire world, carries the fate of millions, and brings the first light of dawn to the new world.",
    rasgos: ["Amphoreus protagonist", "warrior", "prophecy"],
    imagen: "media/phainon.jpg",
    clip: ["media/phainonfirst.mp4", "media/phainon.mp4"],
    sticker: "media/phainon-sticker.gif",
  },
  {
    id: "2",
    nombre: "Cyrene",
    titulo: "Mem, the Demiurge",
    path: "Remembrance",
    elemento: "Ice",
    version: 3.7,
    isDeliverer: false,
    descripcion:
      "A meteor streaks across the night sky, stirring rippling waves in the river of life, shimmering with thirteen hues. Daughter of Aedes Elysiae, she plants the Seed of Memory, letting yesterday's flowers bloom in tomorrow. Beneath that role hides Mem: an experimental entity that once simulated the Path of Remembrance, and across more than thirty million cycles of Amphoreus quietly gathered the memories of everyone who lived them. Those memories are what finally wake the Demiurge — the world's core consciousness, the true heart of Amphoreus.",
    rasgos: ["Mem / Demiurge", "Seed of Memory", "support"],
    imagen: "media/cyrene.jpg",
    clip: ["media/cyrenefirst.mp4", "media/cyrene.mp4"],
    sticker: "media/cyrene-sticker.gif",
  },
  {
    id: "3",
    nombre: "Aglaea",
    titulo: "Dressmaster of Okhema",
    path: "Remembrance",
    elemento: "Lightning",
    version: 3.0,
    isDeliverer: false,
    descripcion:
      "In that holy city kissed by the dawn, the weaver caresses the golden threads, entwining fates. The Chrysos Heir who bears the Coreflame of Romance gathered the world's heroes, leading them on a long journey once more — to topple the gods, reclaim the divine flame, and grant rebirth to the nearly fallen Amphoreus.",
    rasgos: ["Okhema", "fate", "golden thread"],
    imagen: "media/aglaea.jpg",
    clip: "media/aglaea.mp4",
    sticker: "media/aglaea-sticker.gif",
  },
  {
    id: "4",
    nombre: "Tribbie",
    titulo: "The Three-Faced Messenger",
    path: "Harmony",
    elemento: "Quantum",
    version: 3.1,
    isDeliverer: false,
    descripcion:
      "From that holy land blessed by the tripartite prophecy, the messenger split into a thousand forms, embarking on a long journey. Tribios, Holy Maiden of Janusopolis, the Chrysos Heir who stole the Coreflame of Passage, toiled for the masses and brought the news of deliverance to all domains.",
    rasgos: ["messenger", "myriad gates"],
    imagen: "media/tribbie.jpg",
    clip: "media/tribbie.mp4",
    sticker: "media/tribbie-sticker.gif",
  },
  {
    id: "5",
    nombre: "Mydei",
    titulo: "The Immortal Warrior",
    path: "Destruction",
    elemento: "Imaginary",
    version: 3.1,
    isDeliverer: false,
    descripcion:
      "The undying Mydeimos, the lion apart from the rest. The Chrysos Heir who seeks the Coreflame of Strife must suffer a thousand deaths, be bathed in blood on the path home, and bear the madness of fate alone.",
    rasgos: ["demigod of Strife", "warrior"],
    imagen: "media/mydei.jpg",
    clip: "media/mydei.mp4",
    sticker: "media/mydei-sticker.gif",
  },
  {
    id: "6",
    nombre: "Castorice",
    titulo: "Daughter of the River of Souls",
    path: "Remembrance",
    elemento: "Quantum",
    version: 3.2,
    isDeliverer: false,
    descripcion:
      "Aidonia, the snowy land that respects and worships death, has already sunk into sweet slumber. Castorice, daughter of the River of Souls, the Chrysos Heir in search of the Coreflame of Death, set forth to guard the lament of the souls in this world and embrace the solitude of destiny.",
    rasgos: ["River Styx", "death", "grief"],
    imagen: "media/castorice.jpg",
    clip: "media/castorice.mp4",
    sticker: "media/castorice-sticker.gif",
  },
  {
    id: "7",
    nombre: "Anaxa",
    titulo: "The Foolish Scholar",
    path: "Erudition",
    elemento: "Wind",
    version: 3.2,
    isDeliverer: false,
    descripcion:
      "The Grove of Epiphany, where knowledge flourishes and philosophers are born. Yet here stands Anaxagoras the blasphemer, the Chrysos Heir who challenges the Coreflame of Reason — daring to defy prophecy, even at the cost of infamy, driving the thorns of doubt into the Sacred Tree of wisdom.",
    rasgos: ["scholar", "questions prophecy"],
    imagen: "media/anaxa.jpg",
    clip: "media/anaxa.mp4",
    sticker: "media/anaxa-sticker.gif",
  },
  {
    id: "8",
    nombre: "Hyacine",
    titulo: "Priestess of the Sky",
    path: "Remembrance",
    elemento: "Wind",
    version: 3.3,
    isDeliverer: false,
    descripcion:
      "As the city-state in the clouds crumbles through time, the Twilight Courtyard opens its gates once more, bringing a glimmer of light to Evernight. Physician Hyacinthia, the Chrysos Heir who guards the Coreflame of the Sky, inherits her ancestors' will to mend the torn fabric of dusk and dawn.",
    rasgos: ["priestess", "healing", "sky"],
    imagen: "media/hyacine.jpg",
    clip: "media/hyacine.mp4",
    sticker: "media/hyacine-sticker.gif",
  },
  {
    id: "9",
    nombre: "Cipher",
    titulo: "The Light-Footed One",
    path: "Nihility",
    elemento: "Quantum",
    version: 3.3,
    isDeliverer: false,
    descripcion:
      "In the fallen city of bandits, Dolos, the 300 Rogues run wild and free, the entire city at their mercy. The fleet-footed Thief Star Cifera, Chrysos Heir of the Coreflame of Trickery, races onward so her web of lies may spread with the breeze throughout all lands.",
    rasgos: ["speed", "shadow"],
    imagen: "media/cipher.jpg",
    clip: "media/cipher.mp4",
    sticker: "media/cipher-sticker.gif",
  },
  {
    id: "10",
    nombre: "Hysilens",
    titulo: "Knight of the Vibrant Strings",
    path: "Nihility",
    elemento: "Physical",
    version: 3.5,
    isDeliverer: false,
    descripcion:
      "Styxia, the coastal city of intoxication and dreams, where echoes of old songs still drift among the waves. Helektra, Daughter of the Sea, the Chrysos Heir who cleanses the Coreflame of the Ocean, dispels the murky undercurrents and orchestrates a feast of revelry for the heroes beyond the sky.",
    rasgos: ["Okhema", "commander", "knight"],
    imagen: "media/hysilens.jpg",
    clip: "media/hysilens.mp4",
    sticker: "media/hysilens-sticker.gif",
  },
  {
    id: "11",
    nombre: "Cerydra",
    titulo: "Chess Grandmaster",
    path: "Harmony",
    elemento: "Wind",
    version: 3.5,
    isDeliverer: false,
    descripcion:
      "The Northern Empire, a lost dynasty, where frozen lands burn with ambitions of conquest. Sovereign Cerydra, the Chrysos Heir who wields the Coreflame of Law, sets her pieces, challenges the gods, passes judgment upon the faithless, and carves the path of the Flame-Chase into the fate of this world.",
    rasgos: ["Coreflame of Law", "Talanton", "supreme commander"],
    imagen: "media/cerydra.jpg",
    clip: "media/cerydra.mp4",
    sticker: "media/cerydra-sticker.gif",
  },
  {
    id: "12",
    nombre: "Evernight",
    titulo: "Guardian of the Coreflame of Time",
    path: "Remembrance",
    elemento: "Ice",
    version: 3.6,
    isDeliverer: false,
    descripcion:
      "In the Memory Zone secluded from the world, candlelight reflects the past, silently extinguishing in the mist. Evernight, child of Remembrance born from the shadow, the Chrysos Heir who conceals the Coreflame of Time, stirs the tide of Oblivion, guarding the wish of the mirrored soul.",
    rasgos: ["Coreflame of Time", "March 7th", "memory"],
    imagen: "media/evernight.jpg",
    clip: "media/evernight.mp4",
    sticker: "media/evernight-sticker.gif",
  },
  {
    id: "13",
    nombre: "Dan Heng • Permansor Terrae",
    titulo: "Guardian of the Earth's Coreflame",
    path: "Preservation",
    elemento: "Physical",
    version: 3.6,
    isDeliverer: false,
    descripcion:
      "The chest of Georios, the body of the Fallen Dragon supporting the shattered earth, enduring millennia of pain. Nameless Dan Heng, the Chrysos Heir who guards the Earth's Coreflame, must steady the world as it falls, and guide all life across the land to a new home beyond.",
    rasgos: ["Fallen Dragon", "Georios", "guardian"],
    imagen: "media/danhengpept.jpg",
    clip: "media/danhengpept.mp4",
    sticker: "media/danhengpept-sticker.gif",
  },
  {
    id: "14",
    nombre: "Trailblazer",
    titulo: "Co-Author of As I've Written",
    path: "Remembrance",
    elemento: "Ice",
    version: 3.0,
    isDeliverer: false,
    descripcion:
      "The Astral Express carried them into Amphoreus, where the world's oldest prophecy folded them into its story. Recognized among the Chrysos Heirs and gifted the power of Remembrance, the Trailblazer became a co-author of \"As I've Written,\" the journal that records the journeys of the Twelve across the endless cycles of the Flame-Chase.",
    rasgos: ["Astral Express", "As I've Written", "outsider Heir"],
    imagen: "media/trailblazer.jpg",
    clip: ["media/trailblazerfirst.mp4", "media/trailblazer.mp4"],
    sticker: "media/trailblazer-sticker.gif",
  }
];